workflows:
  android-workflow:
    name: Build Grocery Basket APK
    max_build_duration: 30
    environment:
      java: 17
    scripts:
      - name: Give gradlew permission
        script: chmod +x gradlew
      - name: Clean project
        script: ./gradlew clean
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
